config/routes.rb
Rails.application.routes.draw do
  root "static_pages#root"

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: {format: :json} do
    resources :users, only: [:new, :create, :show, :index]
    resource :sessions, only: [:show]
    resources :games
  end
end

app/models/api.rb
module Api
  def self.table_name_prefix
    'api_'
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user,
  primary_key: :id,
  foreign_key: :user1,
  class_name: "User"

  belongs_to :user,
  primary_key: :id,
  foreign_key: :user2,
  class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, :username, uniqueness: true

  has_many :games,
  primary_key: :id,
  foreign_key: :user1,
  class_name: "Game"

  has_many :games,
  primary_key: :id,
  foreign_key: :user2,
  class_name: "Game"
  
  # has_many :fans,
  # primary_key: :id,
  # foreign_key: :liked_id,
  # class_name: "Like"
  #
  # has_many :sent_messages,
  # primary_key: :id,
  # foreign_key: :sender_id,
  # class_name: "Message"
  #
  # has_many :received_messages,
  # primary_key: :id,
  # foreign_key: :receiver_id,
  # class_name: "Message"

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  # def self.capitalize_username(username)
  #   username = username.split(" ")
  #   username.each do |word|
  #     p word
  #     word.capitalize!
  #   end
  #   p username
  #   username = username.join(" ")
  # end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/api/games_controller.rb
class Api::GamesController < ApplicationController
  def index
    @games = Game.all
    render :index
  end

  def create
    @game = Game.create!(game_params)
    render :index
  end

  def edit
    render :show
  end

  def update
    @game = Game.find(params[:id])
    @game.update_attributes(game_params)
    render :update
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    render :index
  end

  private

  def game_params
    params.require(:game).permit(:user1, :user2, :winner, :comments1, :comments2)
  end
end

app/controllers/api/sessions_controller.rb
class Api::SessionsController < ApplicationController

  def show
    render json: current_user
  end

  def profile_params
    params.require(:user).permit(:username,:id)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def new
  end

  def index
    @users = User.all
    render :index
  end

  def create
    @user = User.create!(profile_params)
    render :show
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def edit
    render :show
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(profile_params)
    render :update
  end

  private

  def profile_params
    params.require(:user).permit(:username,:id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  private
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_token!
  end

  def sign_out
    current_user.try(:reset_token!)
    session[:session_token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  attr_reader :current_user

  def create
    @current_user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if @current_user
      sign_in(@current_user)
      redirect_to root_url
    else
      flash.now[:errors_login] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :create

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors_signup] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :username)
  end
end

app/helpers/api/games_helper.rb
module Api::GamesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    "<input
        type=\"hidden\"
        name=\"authenticity_token\"
        value=\"#{ form_authenticity_token }\">".html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_new_session.html.erb
<div class="splash-body">

  <div class="errors">
    <%= flash[:errors_login].join("<br>").html_safe if flash[:errors_login] %>
    <br/>
  </div>
  <h2 class="new-session">Log In</h2>
  <br>
  <form class="new-session" action="<%= session_url %>" method="post">
    <%= auth_token_input %>
    <input type="text" name="user[username]" placeholder="Username">
    <br>
    <input type="password" name="user[password]" placeholder="Password">
    <br><br>
    <input type="submit" value="Log In">
  </form>

  <a class="new-session" href=" <%= new_user_url %> ">Not a user? Sign up</a>

</div>

app/views/layouts/_new_user.html.erb
<div class="splash-body">

  <div class="errors" id="sign-up">
    <%= flash[:errors_signup].join("<br>").html_safe if flash[:errors_signup] %>
    <br/>
  </div>
  <h2 class="new-user">Sign Up</h2>
  <br>
  <form class="new-user" action="<%= users_url %>" method="post">
    <%= auth_token_input %>
    <input type="text" name="user[username]" placeholder="Username">
    <br>
    <input type="password" name="user[password]" placeholder="Password">
    <br><br>
    <input type="submit" value="Sign Up">
  </form>

  <a class="new-user" href=" <%= new_session_url %> ">Already a user? Log in</a>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>X-Wing</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= csrf_meta_tags %>
  </head>

  <% if signed_in? %>

    <body>
      <header>
        <nav class="header-nav">
          <ul class="header-list">
            <a href= "<%="#/profile/#{current_user.id}"%> " id="user_form"></a>
            <li class="header-list-item"><%= button_to "Sign Out", session_url, :method => :delete %></li>
          </ul>
        </nav>
      </header>
      <%= yield %>
    </body>

  <% else %>

    <%= link_to "Sign Up", new_user_url, class: "btn btn-primary" %>
    <%= link_to "Log In", new_session_url, class: "btn btn-primary" %>
    <%= yield %>

  <% end %>
</html>

app/views/static_pages/root.html.erb
<%= javascript_include_tag 'application'%>
<div id="root">
</div>

app/views/users/new.html.erb
<%= render "./layouts/new_user" %>